version: "3.8"
services:
  edge-service:
    depends_on:
      - polar-redis
      - catalog-service
      - order-service
    image: "edge-service"
    container_name: "edge-service"
    ports:
      - 9000:9000
    environment:
      - SPRING_REDIS_HOST=polar-redis
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - CATALOG_SERVICE_URL=http://catalog-service:9001
      - ORDER_SERVICE_URL=http://order_service:9002

  order-service:
    depends_on:
      - polar-postgres
      - config-service
      - catalog-service
    image: "order-service"
    container_name: "order-service"
    ports:
      - 9002:9002
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_R2DBC_URL=r2dbc:postgresql://polar-postgres:5432/polardb_order
      - SPRING_FLYWAY_URL=jdbc:postgresql://polar-postgres:5432/polardb_order
      - POLAR_CATALOG_SERVICE_URI=http://catalog-service:9001

  catalog-service:
    depends_on:
      - polar-postgres
      - config-service
    image: "catalog-service"
    container_name: "catalog-service"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
      - SPRING_PROFILES_ACTIVE=testdata
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888

  config-service:
    image: "config-service"
    container_name: "config-service"
    ports:
      - 8888:8888

  dispatcher-service:
    depends_on:
      - polar_rabbitmq
    image: dispatcher-service
    container_name: dispatcher_service
    ports:
      - 9003:9003
    environment:
      RABBITMQ_HOST: polar-rabbitmq

  polar-postgres:
    image: "postgres:14.4"
    container_name: "polar-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  polar-redis:
    image: "redis:7.0"
    container_name: "polar_redis"
    ports:
      - 6379:6379

  polar-rabbitmq:
    image: rabbitmq:3.10-management
    container_name: polar_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
