apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/akinwale-habibullah/catalog-service/k8s?ref=main

patches:
- path: patch-env.yml
- path: patch-resources.yml
- path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: catalog-config

images:
- name: catalog-service
  newName: ghcr.io/akinwale-habibullah/catalog-service
  newTag: 2c4c685a4f0493f0df550c76f859aa312b566c8d

replicas:
- count: 2
  name: catalog-service
