apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/akinwale-habibullah/order-service/k8s?ref=main

patches:
- path: patch-env.yml
- path: patch-resources.yml
- path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: order-config

images:
- name: order-service
  newName: ghcr.io/akinwale-habibullah/order-service
  newTag: b8ad65fb3a011bcbe8f2dcd27b1ce5e90022cae3

replicas:
- count: 1
  name: order-service
